### ISSUE TITLE
Problems with batch upload videos (1)

### ISSUE THREAD

**Issue by ocrasborn** [Signbank/NGT-signbank#359] opened 2017-07-31 12:01 UTC
I get an error message (with a spelling error, to not two) for every item that is correctly linked/uploaded. Example: "Failed two overwrite ONTSTAAN-B. Maybe this file is not owned by the webserver?"

**Comment by vanlummelhuizen** [comment] 2017-08-02 09:19
I started off by correcting the typo. Now on to the next problem...

**Comment by vanlummelhuizen** [comment] 2017-08-02 12:10
When I test this on my local Signbank instance, the problem is caused by the fact that Signbank is not able to read the files in the upload folder (it can get the list of files from that folder). The error message only covers the option of not being able to write, not the option of not being able to read. I will at least change the error message for now.

On the server the permissions seem correct. Perhaps this problem is somehow caused by me starting the live Signbank instance instead of @Woseseltops . I will ask @Woseseltops asap if he can detect the problem.

Something to try: when uploading videos to be imported, also set the read permissions for 'other' (public permissions). This is not a real solution of course!

**Comment by vanlummelhuizen** [comment] 2017-08-02 12:14
I also saw that a new video was not resized if there already was a small version. This is solved now.

**Comment by vanlummelhuizen** [comment] 2017-08-03 08:02
Apparently, the Python function that copies the file from the import_videos folder (shutil.copy) also tries to do a chmod. Because the chmod fails, the error pops up. Replacing the function for shutil.copyfile solves this.

This is already live.

Note to self: it still needs to be pushed to git.

**Comment by henrinie** [comment] 2017-08-08 10:09
Partly unrelated, but just wanted to let you know that we _batch upload_ videos from the interface/website.
It is easier for the users and the videos end up directly on the web server. This is probably not as efficient as your way, but perhaps not as complicated.

**Comment by Woseseltops** [comment] 2017-08-25 14:55
Can we close this one @ocrasborn ?

**Comment by ocrasborn** [comment] 2017-08-25 15:00
Ja dus :-)

**Closed** 2017-08-25 15:00 UTC
Labels: ASL, bug, high priority
